export enum EModalVariant {
	CLOSED = 'CLOSED',
	CONFIRMATION = 'CONFIRMATION',
	CONNECT_WALLET = 'CONNECT_WALLET',
	VALIDATOR_STAKE = 'VALIDATOR_STAKE',
	CAMPAIGN_INITIATE = 'CAMPAIGN_INITIATE',
	CAMPAIGN_DEPOSIT = 'CAMPAIGN_DEPOSIT',
	CAMPAIGN_VOTE = 'CAMPAIGN_VOTE',
	CAMPAIGN_DEPOSIT_TIMELINE = 'CAMPAIGN_DEPOSIT_TIMELINE'
}
