name: CI

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        node-version: [20.15.0]
        os: [ubuntu-22.04]

    name: Build
    runs-on: ${{ matrix.os }}
    env:
      PUBLIC_DEFAULT_CHAIN: ${{ secrets.PUBLIC_DEFAULT_CHAIN }}
      PUBLIC_HUB_API: ${{ secrets.PUBLIC_HUB_API }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Configure .npmrc for GitHub Packages
        run: |
          touch .npmrc
          sed -i "s|\${GITHUB_TOKEN}|${{ secrets.GITHUB_TOKEN }}|g" .npmrc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: npm ci
        if: success()

      - name: Run type checks
        run: npm run check
        if: success()

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        if: success()

      - name: Run tests
        id: run-tests
        run: npm run test
        if: success()

      - name: Run tests again if failed
        if: failure()
        id: retry-tests
        run: npm run test

      - name: Run linter
        if: success() || steps.retry-tests.outcome == 'success'
        run: npm run lint
